#!/usr/bin/env python3
import argparse
import os

import mido  # type: ignore

parser = argparse.ArgumentParser()
parser.add_argument("-s", "--soprano", default='soprano.mid')
parser.add_argument("-a", "--alt", default='alt.mid')
parser.add_argument("-t", "--tenor", default='tenor.mid')
parser.add_argument("-b", "--bass", default='bass.mid')
args = parser.parse_args()


solo_midi_files = list(map(lambda
                           midifile_path: mido.MidiFile(midifile_path),
                           [args.soprano, args.alt, args.tenor, args.bass]
                           ))

output_midi = mido.MidiFile()
output_midi.ticks_per_beat = solo_midi_files[0].ticks_per_beat

for solo_midi_file in solo_midi_files:
    number_of_tracks = len(solo_midi_file.tracks)
    # print(f"Has {number_of_tracks} tracks")
    output_midi.tracks.append(solo_midi_file.tracks[0])

output_midi.save('out.mid')
