#!/usr/bin/env python3
import argparse
import sys

import midi_to_part_mp3s
from custom_types import ConfigType, VoiceStringsType
from default_config import default_config


def help_string_for_voice(voice: VoiceStringsType):
    default = default_config[voice][0]
    return f'comma separated list of midi track IDs, defaults to "{default}"'


def get_parser() -> argparse.ArgumentParser:
    def convert_to_list(x): return list(map(int, x.split(',')))

    parser = argparse.ArgumentParser()
    parser.add_argument(
        "-s",
        "--soprano",
        type=convert_to_list,
        help=help_string_for_voice("soprano")
    )
    parser.add_argument(
        "-a",
        "--alto",
        type=convert_to_list,
        help=help_string_for_voice("alto")
    )
    parser.add_argument(
        "-t",
        "--tenor",
        type=convert_to_list,
        help=help_string_for_voice("tenor")
    )
    parser.add_argument(
        "-b",
        "--bass",
        type=convert_to_list,
        help=help_string_for_voice("bass")
    )
    parser.add_argument(
        "-in",
        "--instrument",
        type=int,
        help=('instrument for voices. Defaults to "49"'))
    parser.add_argument("-iv",
                        "--instrumental-volume",
                        help="configure instrumental volume",
                        type=float,
                        default=default_config["instrumental_volume"])
    parser.add_argument("-i",
                        "--instrumental-accompaniment",
                        help='midi tracks that \
          appear in all accompaniment mp3s e.g. piano or orchestra',
                        nargs='+',
                        type=int,
                        default=[])
    required_named = parser.add_argument_group('mandatory argument')
    required_named.add_argument(
        "-f",
        "--file-path",
        required=True,
        help='Input file to generate the tracks from. Can be Midi or \
                            MusicXML (.mid, .midi, .mxl, .musicxml)')
    return parser


if __name__ == "__main__":
    parsed_args = get_parser().parse_args(sys.argv[1:])
    config: ConfigType = {**default_config, **vars(parsed_args)}
    midi_to_part_mp3s.split(config)
