#!/usr/bin/env python3
import mido
import sys
import os

output_directory = "./output"
soundfont_path = "./soundfonts/timbres-of-heaven.sf2"

def track_names(midi_data):
  return list(map(lambda track: track.name, midi_dat.tracks))

def isolate_tracks(midi_data, track_numbers, output_filename):
  new_file = mido.MidiFile()

  for track_number in track_numbers:
    new_file.tracks.append(midi_data.tracks[track_number])

  # TODO: update language to say "part"
  change_instrument(new_file, instrument_number_for_part(output_filename))
  new_file_path = "{}/{}.midi".format(output_directory, output_filename)
  new_file.save(new_file_path)

  return new_file_path

def convert_midi_to_mp3(midifile_path):
  output_base_filename = os.path.splitext(midifile_path)[0]
  temp_wav_file_path = "./temp.wav"
  # TODO: Hide output unless debug option on... probably need subprocess.run
  os.system("fluidsynth -F {} {} {}".format(
    temp_wav_file_path, soundfont_path, midifile_path
  ))
  os.system("lame {} {}.mp3".format(temp_wav_file_path, output_base_filename))
  os.unlink(temp_wav_file_path)

def change_instrument(midi_data, program_number):
  for track in midi_data.tracks:
    for message in track:
      if message.type == 'program_change':
        message.program = program_number

def separate_tracks_into_mp3s(midi_data, description):
  for track_name, track_numbers in description.items():
    convert_midi_to_mp3(isolate_tracks(midi_data, track_numbers, track_name))

def cleanup():
  remove_temporary_midifiles()

def remove_temporary_midifiles():
    for midi_file in os.listdir(output_directory):
        if midi_file.endswith('.midi'):
             os.unlink(os.path.join(output_directory, midi_file))

def instrument_number_for_part(part):
# based off http://www3.cpdl.org/wiki/index.php/User:Robert_Urmann
    return {
            "soprano": 76, # pan flute
            "alt": 75, # recorder
            "tenor": 49, # string ensemble 1
            "bass": 50 # string ensemble 2
            }[part]

midifile_path = sys.argv[1]

# TODO: Document this and make optional
description = {
  "soprano": [0,1],
  "alt": [0,2],
  "tenor": [0,3],
  "bass": [0,4]
}

midi_data = mido.MidiFile(midifile_path)

separate_tracks_into_mp3s(midi_data, description)
remove_temporary_midifiles()
